erDiagram
    USER ||--o| CART : "has (0..1)"
    CART ||--o{ CART_PRODUCT : "contains"
    PRODUCT ||--o{ CART_PRODUCT : "is in"

    USER {
        int id
        string email
        string password_hash
        string firstname 
        string lastname
        UserRole role
    }

    CART {
        int id
        int userId
    }

    PRODUCT {
        int id
        string name
        float price 
        string description 
        DATETIME created_at 
        DATETIME updated_at
    }

    CART_PRODUCT {
        int cartId
        int productId
        int quantity
    }
