"""Fix id in table

Revision ID: f459a66ea9d2
Revises: fbc89ad4c5f8
Create Date: 2025-09-16 21:51:49.525312

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f459a66ea9d2"
down_revision: Union[str, Sequence[str], None] = "fbc89ad4c5f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column("carts", "created_at", type_=sa.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column("carts", "updated_at", type_=sa.TIMESTAMP(timezone=True), nullable=True)

    op.execute("""
    CREATE OR REPLACE FUNCTION set_carts_created_at()
    RETURNS TRIGGER AS $$
    BEGIN
        NEW.created_at = NOW();
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    DROP TRIGGER IF EXISTS set_carts_created_at_trigger ON carts;
    """)
    op.execute("""
    CREATE TRIGGER set_carts_created_at_trigger
    BEFORE INSERT ON carts
    FOR EACH ROW
    EXECUTE FUNCTION set_carts_created_at();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column(
    #    'carts',
    #    'id',
    #    existing_type=UUID(as_uuid=True),
    #    server_default=None,
    #    existing_nullable=False
    # )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("carts", "created_at", type_=sa.TIMESTAMP(timezone=False), nullable=False)
    op.alter_column("carts", "updated_at", type_=sa.TIMESTAMP(timezone=False), nullable=True)

    op.execute("DROP TRIGGER IF EXISTS set_carts_created_at_trigger ON carts;")
    op.execute("DROP FUNCTION IF EXISTS set_carts_created_at();")
    # ### end Alembic commands ###
