from .users import api_v1_users
from .auth import api_v1_auth
from .products import api_v1_products
from .carts import api_v1_carts
from .files import static_files
from .notifications import api_v1_notifications
from .admin import api_v1_admin
from .orders import api_v1_orders
from .order_addresses import api_v1_order_addresses 
from .order_items import api_v1_order_items
